//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efsemop.Framework.Pepemosca.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAlcaldia
    {
        public int IdSubAlcaldia { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Zona { get; set; }
        public string Telefono { get; set; }
        public string NombreSubAlcalde { get; set; }
    }
}
